language: node_js
sudo: false
notifications:
  email: false
cache:
  directories:
    - node_modules
node_js:
  - '5'
script:
  - npm run ci
after_success:
  - npm run report-cover
  - npm run semantic-release
