language: node_js
sudo: false
notifications:
  email: false
cache:
  directories:
    - node_modules
node_js:
  - '5'
  - '10'
script:
  - npm run ci
after_success:
  - npm run report-cover
  - npm run semantic-release
before_deploy:
  - npm config set spin false --global
deploy:
  provider: npm
  email: public@asciidisco.com
  skip_cleanup: true
  on:
    branch: master
    repo: asciidisco/serveit2
